version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto_config/mosquitto.conf:/mosquitto/config/mosquitto.conf



  temperature_sensor_albert:
    build:
      context: ./
      dockerfile: ./simulators/temperature_sensor/Dockerfile
    container_name: temperature_sensor_albert
    environment:
      - MQTT_BROKER=mosquitto
      - USER_ID=1234
    depends_on:
      - mosquitto
      - kafka

  presence_sensor_albert:
    build:
      context: ./
      dockerfile: ./simulators/presence_sensor/Dockerfile
    container_name: presence_sensor_albert
    environment:
      - MQTT_BROKER=mosquitto
      - USER_ID=1234
    depends_on:
      - mosquitto
      - kafka

#  gateway_albert:
#    build:
#      context: ./gateways
#    container_name: gateway_albert
#    environment:
#      - MQTT_BROKER=mosquitto
#      - USER_ID=1234
#    depends_on:
#      - mosquitto
#      - temperature_sensor_albert
#      - presence_sensor_albert

#  cloud_ingestor:
#    build:
#      context: ./cloud_microservices/cloud_ingestor
#    container_name: cloud_ingestor
#    depends_on:
#      - mosquitto

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper


  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
