# Dockerfile for Temperature and Presence Simulators
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy necessary files into the container
COPY timeseries_get.py /app/timeseries_get.py
COPY mqtt_publisher.py /app/mqtt_publisher.py

# Install necessary dependencies
RUN pip install paho-mqtt

# Run the publisher script
CMD ["python", "mqtt_publisher.py"]
